### ISSUE TITLE
Find/replace

### ISSUE THREAD

**Issue by AcckiyGerman** [AcckiyGerman/tabulator-py#2]
As a data curator I want to be able to find some strings and replace them automatically when processing data, so I don't need to do it manually.  

## dataset examples 
https://github.com/datasets/cash-surplus-deficit/blob/master/scripts/process.py [lines 27,28]  
https://github.com/datasets/co2-ppm/blob/master/scripts/process.sh [line 42]  
https://github.com/datasets/gdp-us/blob/master/scripts/process.py [lines 36-45] 

## Tasks

* [x] analyze [30m]
* [x] learn tabulator-py docs, run examples [20m]

* [ ] write tests for a new processor [20m]
* [ ] create the function [25m]

* [ ] do post-review fixes [20m]

Overall [4 to 4.5h]

## Analyse
We can create replace function in two ways:
* [ ] Pass 'replace' function into Stream constructor as a **post_parse** argument
* [ ] open **stream** and pass it into 'replace' function as argument

Then we need to:
* [ ] define the place to store complex functions like 'replace', 'unpivot' etc.

### replace arguments format
* I will use a dictionary to pass agruments into 'replace' function, so later we could extend agruments with more keywords:  
`replace={'old': 'q1', 'new': '-03-31'}`
* For several replacements we could use a list of dictionaries: 
```python
replace=[
    {'old': 'q1', 'new': '-03-31'},
    {'old': 'q2', 'new': '-06-30'}
]
```

* [ ] [+2h] To enable RegExp we could pass `'regex': True`. Here's a real example from the script, that need an automation: `replace('\.|"|,|\'|:|-|\(|\)', '', regex=True)`. 
In such case the parameter will look like that:
```python
replace={
    'old': '\.|"|,|\'|:|-|\(|\)',
    'new': '',
    'regex': True
}
```

* [ ] [+2h] We could specify column to apply replace function to. (e.g we need to replace 'q1' to '-03-31' but there could be 'q1' in other columns, that we does not want to break)
```python
replace={'old': 'q1',
         'new': '-03-31',
         'regex': True,
        'column': N or 'name'}
```

**Comment by AcckiyGerman** [comment]
## replace command interface discussion
- syntax similar to python string.replace method: `replace: [old, new]`
- RegEx support e.g. `replace: [old, new, regex=true]` or `replace: [old, new, regex]
- several replacements: `replace: [old, new], [old2, new2] ...` or
```
# will Yaml parser accept this? As I know the parser will use this arguments to pass into
# the Stream, and we couldn't pass two agruments with the same name.
replace: [old, new]
replace: [old2, new2]
```
- ability to chose the column to apply the replacement: `replace: [old, new, column=N]` or `replace: [old,new, column='name']`

**Comment by Mikanebu** [comment]
Is it possible to pass something like a list of dicts.
```
replace: [{'old1': './', 'new1': '&'}, {'old2': '...', 'new2': '.,.'}]
```
or a list of lists
```
replace: [['old', 'new'], ['testNew1', 'test1'], ['testNew2', 'test2']]
```
What do you think?

**Comment by AcckiyGerman** [comment]
I don't know, reading https://github.com/frictionlessdata/datapackage-pipelines now.
Also I like this format:
![tabulator yaml](https://user-images.githubusercontent.com/11707682/34155676-a0d20b12-e4ba-11e7-9a5d-424546ce44c5.png)

**Comment by AcckiyGerman** [comment]
Analyse updated, thanks @Mikanebu , @zelima

**Comment by akariv** [comment]
Could you provide dataset that may need this? 
I agree that `tabulator` is not the place for this (as it doesn't do 'wrangling' in any other way, only extraction of data from tabular files).
Last - why is this issue open here? @zelima

**Comment by AcckiyGerman** [comment]
Frictionless guys rejected the issue.
The reason is - the Stream constructor is a wrong place for integrating complex functions.
The proper place is **post_parse**

Now the question is - extend 'pipelines' so it could use the 'post_parse' to include complex data wranglings in there.

**Comment by AcckiyGerman** [comment]
Analyse is updated.

**Comment by akariv** [comment]
@AcckiyGerman 
Could you provide dataset that may need this?

The quarters example is no good - they should be parsed as another date format (as year, yearmonth etc), not converted to a simple date.

**Comment by AcckiyGerman** [comment]
> https://github.com/datasets/cash-surplus-deficit/blob/master/scripts/process.py [lines 27,28]
```python
 df['Country Name'] = df['Country Name'].replace('\.|"|,|\'|:|-|\(|\)', '', regex=True)
 df['Country Name'] = df['Country Name'].replace('&', 'AND', regex=True)
```
> https://github.com/datasets/co2-ppm/blob/master/scripts/process.sh [line 42]
```bash
    # replace underscores with dashes
    sed 's/_/-/g' | \
    # replace txt extension with csv
    sed 's/\.txt$/.csv/'
```

**Comment by akariv** [comment]
Do you know why these search & replaces are necessary in the first example?
To me they do not seem that important - mostly cosmetic fixes.

I think that without a concrete example that shows this is needed we should move this to the icebox.

**Comment by AcckiyGerman** [comment]
Task is frozen unless we have more datasets with replace need.

**Comment by AcckiyGerman** [comment]
FIXED:
Implemented: https://github.com/frictionlessdata/datapackage-pipelines#find_replace
