### ISSUE TITLE
Unzip data from zipped source

### ISSUE THREAD

**Issue by AcckiyGerman** [AcckiyGerman/tabulator-py#3]
As a user I want to unzip packages automatically to process the data files inside, so I don't need to do it manually.

## Acceptance Criteria 

* [ ] pipeline processor can unzip files for processing
* [ ] frictionless data accept the pull request.

## Tasks

* [x] analyze [20m]
* [ ] learn pipeline docs, run examples [1.5h]
* [ ] find and analyse the where the `resource-mapping` is processed [20m]
* [ ] write tests for Unzip processor [30m]
* [ ] create the function [30m]
* [ ] check all the old and new tests are working [10m]
* [ ] update the docs [20m]
* [ ] do post-review fixes [20m]
* [ ] PR to main repo [10m]
* [ ] fix the PR post-review fixes, if any [0..20m]
Overall [4 to 4.5h]

## Analysis 
Existing Zip support in tabulator-py works only for python3 at the moment.  
I think we should be able to specify a mask for files in ZIP to be processed, e.g. `*.csv, *.xlsx`, coz files in a Zip may change their names depending of date, version etc. am I right?

* [ ] Q: Should user provide a file mask OR a file-name OR unzip-processor will process all files in the archive?
A: I would expect instructions for this form you.  Depends what is the exact user story

@Mairan plz write an usecase example for this question

**Comment by AcckiyGerman** [comment]
As we could see from the tabulator code:
![image](https://user-images.githubusercontent.com/11707682/34438638-8d169f3e-eca8-11e7-846b-45a63274161b.png)
The first file inside the zip will be used as a source
