### ISSUE TITLE
Pivot / unpivot

### ISSUE THREAD

**Issue by AcckiyGerman** [AcckiyGerman/tabulator-py#4]
As a user, I want to change places of columns and rows so it wouldn't have to be done each time manually 

## Acceptance criteria

* [ ] output file has raplaced places of columns and  rows

## Tasks

* [ ] pull request for tabulator-py [0.5h]
* [ ] analysis of tabulator-py [1h]
* [ ] Write failing tests
* [ ] in stream class add pivot
    * [ ] add pivot as parameter
    * [ ] add pivot function
* [ ] Check if test are passing
* [ ] pull request to main repo [0.5h]

## Analysis 

Like it is done for any parameter like that it will be done for pivot in this file
https://github.com/frictionlessdata/tabulator-py/blob/master/tabulator/stream.py

@acckiygerman think that unpuvot feature suits better in the datapackage-py, because tabulator *streams* iterates the data row by row processing rows via several python generators, but at one moment there are only one row loaded (nothing to pivot).  
But! what if we create a generator, which creates columns in the memory while iterating via source, and in the end dumps it to the disk/replacing rows?  
Will try to do like that.

**Comment by AcckiyGerman** [comment]
FIXED: https://github.com/frictionlessdata/datapackage-pipelines#unpivot
